### ISSUE TITLE
Main.CommonFunc

### ISSUE THREAD

**Issue by Rik69** [HemulGM/ColorToStrNew#1]
Hi,

Can you tell me where I can find Main.CommonFunc from use clause in CTS.Main

Thank you

Erik

**Comment by HemulGM** [comment]
Fixed it, thx

**Comment by HemulGM** [comment]
> Hi,
> 
> Can you tell me where I can find Main.CommonFunc from use clause in CTS.Main
> 
> Thank you
> 
> Erik

fixed
